[package]
name = "wasm-graph-visualizer"
version = "0.1.0"
edition = "2018"

[dependencies]
oxigraph = "0.3"
wasm-bindgen = "0.2"
js-sys = "0.3"
petgraph = "0.6"
once_cell = "1.10"
anyhow = "1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-pack = { version = "0.10.0", optional = true }
